#' Toy Drift Diffusion Model
#'
#' A function to run and visualize the results of a drift diffusion model.
#' Serves as a wrapper for an internal function, [diffusion_sim]. Though this
#' function is useful for visualizing and understanding drift diffusion models
#' and the influence different parameters have on simulated results, models
#' generated by this function are produced from random data and are ultimately
#' not practically informative.
#'
#' @param nsims An integer (1000 by default). The number of simulations to run.
#' @inheritParams diffusion_sim
#' @param plots Logical (TRUE by default). Should plots be generated when the
#'  model is run?
#' @param show_legend Logical (FALSE by default). Should the legend be shown
#'  on the evidence plot?
#' @param ... Optional arguments to be passed to `'theme_pcj()'` which is used to
#'  style the generated plots.
#' @returns Returns a list containing:
#'    * The results of the simulation
#'    * A density plot of evidence accumulation over time
#'    * A plot of the rt distributions for one outcome over the other
#'    * The RT quintile-probability plot for each decision with points at the
#'      0.1, 0.3, 0.5, 0.7, and 0.9 quintiles
#' @references Farrell, S., & Lewandowsky, S. (2018). Computational modeling of cognition and behavior. Cambridge University Press.
#' @export
#' @examples
#' \donttest{
#' # Run simulation with default parameters
#' results <- drift_mod()
#'
#' # Access simulation data
#' results$sim_results
#'
#' # Run without plots
#' results <- drift_mod(nsims = 100, plots = FALSE)
#'
#' # Show legend on evidence plot
#' results <- drift_mod(nsims = 100, show_legend = TRUE)
#' }
drift_mod <- function(nsims = 1000, v = 0.5, sv = 0, a = 2, w = 0.5, sw = 0.9,
                      t0 = 0, st0 = .2, dt = .01, t_max = Inf, plots = TRUE,
                      show_legend = FALSE, ...) {

# Initialize and Run Simulation -------------------------------------------

  # Initially empty, this will save the random walk simulations
  sim_results <- c()

  for (i in 1:nsims) {
    # Simulate a single realization of the random walk with the given parameters
    current_result <- diffusion_sim(v, sv, a, w, sw, t0, st0, dt, t_max)
    # "Bind" the each simulation to the record of results
    sim_results <- rbind(
      sim_results,
      # Add a new column that identifies each simulation
      current_result[, sim_index := i]
    )
  }

# Visualize Simulation Results --------------------------------------------

  if (plots == TRUE) {
    # Extract simulated choices and RT's
    choice_rt <- sim_results[, `:=`(choice = ifelse(data.table::last(x) > 0, "upper", "lower"),
                                    rt = data.table::last(t)),
                             by = sim_index]

    # Quantile-probability plot
    sim_choice_p <- choice_rt[, .N, by = choice][, p_resp := N / sum(N)]
    qprobs <- c(0.1, 0.3, 0.5, 0.7, 0.9)
    sim_rt_q <- choice_rt[, list(rt_q = stats::quantile(x = rt, probs = qprobs)),
                          by = choice]

    # Visualize the internal evidence states
    fp1 <- ggplot2::ggplot(
      data = sim_results,
      mapping = ggplot2::aes(
        x = t,
        y = x)
    ) +
      ggplot2::stat_density2d_filled(show.legend = show_legend) +
      theme_pcj() +
      ggplot2::labs(
        title = "Internal Evidence States Over Time",
        ylab = "Accumulated Evidence",
        xlab = "Time",
        fill = "Relative frequency"
      )

    # Plot conditional RT distributions
    fp2 <- ggplot2::ggplot(
      data = choice_rt,
      mapping = ggplot2::aes(
        x = rt,
        fill = choice,
        alpha = .1)
    ) +
      ggplot2::geom_density() +
      ggplot2::guides(alpha = "none") +
      theme_pcj() +
      ggplot2::labs(
        title = "Conditional RT Distributions",
        subtitle = "",
        ylab = "Frequency",
        xlab = "Response Time",
        color = "Choice"
      )

    # Plot the quantiles of the upper and lower response distributions
    fp3 <- ggplot2::ggplot(
      data = dplyr::full_join(sim_choice_p, sim_rt_q, by = "choice"),
      mapping = ggplot2::aes(
        x = p_resp,
        y = rt_q,
        color = choice)
    ) +
      ggplot2::geom_point() +
      ggplot2::scale_x_continuous(
        limits = c(0, 1),
        expand = ggplot2::expansion(mult = 0.05)
      ) + theme_pcj() +
      ggplot2::labs(
        title = "Quantile-Probability Plot",
        subtitle = "",
        ylab = "RT Quantile",
        xlab = "Response Proportion"
      )

    # Build results list with plots
    results <- list(
      sim_results = sim_results,
      `Evidence Plot` = fp1,
      `RT Dist` = fp2,
      `Quantile Plot` = fp3
    )

  } else {
    # Build results list without plots
    results <- list(
      sim_results = sim_results
    )
  }

  return(invisible(results))
}